version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 28018:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/monogo-init.js:ro
  backend:
    build: ./API
    ports:
      - 8000:8000
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - SECRET_KEY=secret
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - 4200:80
    depends_on:
      - backend
