---
openapi: 3.0.0
info:
  title: Simple Zero Trust Network Access API
  contact:
    email: mabaums@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: http://localhost:8000
  description: SwaggerHub API Auto Mocking
tags:
- name: authentication
  description: Calls made to authenticate users
- name: apps
  description: Calls made regarding available apps
paths:
  /users/login:
    post:
      tags:
      - authentication
      operationId: login
      requestBody:
        description: Email
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/users_login_body'
        required: true
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                type: string
        "500":
          description: interal server error
          content:
            application/json:
              schema:
                type: string
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: string
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
  /users/apps:
    get:
      tags:
      - apps
      operationId: getApps
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
components:
  schemas:
    users_login_body:
      type: object
      properties:
        Token:
          type: string
